package webProject.server.daily;
/**
* AnyQuantProject/webProject.server.daily/S.java
* @author cxworks
* 2016年5月5日 下午8:38:55
*/
public class Q {
	
	
	public static final String Create="CREATE TABLE IF NOT EXISTS ";
	static class Bench{
		public static final String truncate="TRUNCATE TABLE benchmark;";
		public static final String create="CREATE TABLE IF NOT EXISTS benchmark ( "
				+ "date date not null, "
				+ "benchmark_id varchar(10) , "
				+ "benchmark_name varchar(20), "
				+ "open double default 0, "
				+ "high double default 0, "
				+ "low double default 0, "
				+ "close double default 0, "
				+ "volumn int default 0, "
				+ "adj_price double default 0,  "
				+ "transaction bigint default 0, "
				+ "marketvalue bigint default 0, "
				+ "flow bigint default 0, "
				+ "PMA5_day double default 0, "
				+ "PMA5_week double default 0, "
				+ "PMA5_month double default 0, "
				+ "PMA10_day double default 0, "
				+ "PMA10_week double default 0, "
				+ "PMA10_month double default 0, "
				+ "PMA30_day double default 0, "
				+ "PMA30_week double default 0, "
				+ "PMA30_month double default 0, "
				+ "RSI6 double default 0, "
				+ "RSI12 double default 0, "
				+ "RSI24 double default 0, "
				+ "BIAS6 double default 0, "
				+ "BIAS12 double default 0, "
				+ "BIAS24 double default 0, "
				+ "K double default 0, "
				+ "D double default 0, "
				+ "J double default 0, "
				+ "DIF double default 0, "
				+ "DEA double  default 0, "
				+ "MACDBar double default 0, "
				+ "poly double default 0, "
				+ "primary key(date)) "
		 		+ "ENGINE=InnoDB DEFAULT CHARSET=utf8;";
		
		public static final String insert="INSERT INTO benchmark ( "
				+ "date , "
				+ "benchmark_id , "
				+ "benchmark_name , "
				+ "open , "
				+ "high , "
				+ "low , "
				+ "close , "
				+ "volumn , "
				+ "adj_price , "
				+ "transaction , "
				+ "marketvalue , "
				+ "flow , "
				+ "PMA5_day , "
				+ "PMA5_week , "
				+ "PMA5_month , "
				+ "PMA10_day , "
				+ "PMA10_week , "
				+ "PMA10_month , "
				+ "PMA30_day , "
				+ "PMA30_week , "
				+ "PMA30_month , "
				+ "RSI6 , "
				+ "RSI12 , "
				+ "RSI24 , "
				+ "BIAS6 , "
				+ "BIAS12 , "
				+ "BIAS24 , "
				+ "K , "
				+ "D , "
				+ "J , "
				+ "DIF , "
				+ "DEA , "
				+ "MACDBar , "
				+ "poly "
				+ ") "
				+ "VALUES ( "
				+ "? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , "
				+ "? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? "
				+ ");";
		
		public static final String select="SELECT "
				+ "date , "
				+ "open , "
				+ "high , "
				+ "close , "
				+ "low "
				+ "FROM benchmark WHERE date >= ? ORDER BY date ;";
	}
	
	static class Stock{
		public static final String del="DELETE FROM ";
		public static final String deltail=" WHERE date >= ? ;";
		
		
		public static final String createToday="CREATE TABLE IF NOT EXISTS today ( "
				+ "stock_id varchar(10) not null , "
				+ "stock_name varchar(20), "
				+ "open double default 0, "
				+ "high double default 0, "
				+ "low double default 0, "
				+ "close double default 0, "
				+ "volumn int default 0, "
				+ "adj_price double default 0,  "
				+ "turnover double default 0,  "
				+ "pe_ttm double default 0,  "
				+ "pb double default 0,  "
				+ "industry varchar(20), "
				+ "PMA5_day double default 0, "
				+ "PMA5_week double default 0, "
				+ "PMA5_month double default 0, "
				+ "PMA10_day double default 0, "
				+ "PMA10_week double default 0, "
				+ "PMA10_month double default 0, "
				+ "PMA30_day double default 0, "
				+ "PMA30_week double default 0, "
				+ "PMA30_month double default 0, "
				+ "RSI6 double default 0, "
				+ "RSI12 double default 0, "
				+ "RSI24 double default 0, "
				+ "BIAS6 double default 0, "
				+ "BIAS12 double default 0, "
				+ "BIAS24 double default 0, "
				+ "K double default 0, "
				+ "D double default 0, "
				+ "J double default 0, "
				+ "DIF double default 0, "
				+ "DEA double  default 0, "
				+ "MACDBar double default 0, "
				+ "poly double default 0, "
				+ "primary key(stock_id) ) "
				+ "ENGINE=InnoDB DEFAULT CHARSET=utf8;";
		public static final String truncate="TRUNCATE TABLE today;";
		public static final String insertToday="INSERT INTO today ( stock_id , "
				+ "stock_name , "
				+ "open , "
				+ "high , "
				+ "low , "
				+ "close , "
				+ "volumn , "
				+ "adj_price , "
				+ "turnover , "
				+ "pe_ttm , "
				+ "pb , "
				+ "industry , "
				+ "PMA5_day , "
				+ "PMA5_week , "
				+ "PMA5_month , "
				+ "PMA10_day , "
				+ "PMA10_week , "
				+ "PMA10_month , "
				+ "PMA30_day , "
				+ "PMA30_week , "
				+ "PMA30_month , "
				+ "RSI6 , "
				+ "RSI12 , "
				+ "RSI24 , "
				+ "BIAS6 , "
				+ "BIAS12 , "
				+ "BIAS24 , "
				+ "K , "
				+ "D , "
				+ "J , "
				+ "DIF , "
				+ "DEA , "
				+ "MACDBar , "
				+ "poly "
				+ ") "
				+ "VALUES ( "
				+ "? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , "
				+ "? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? "
				+ ");";
		public static final String selectStock="SELECT "
				+ "date , "
				+ "open , "
				+ "high , "
				+ "close , "
				+ "low , "
				+ "volumn , "
				+ "adj_price , "
				+ "turnover , "
				+ "pe_ttm , "
				+ "pb , "
				+ "industry , "
				+ "stock_name "
				+ "FROM ";
		public static final String seleTail=" where date >= ? ORDER BY date;";
		
	}
	
	static class Industry{
		public static final String tailIndustry=" ( "
				+ "industry_name varchar(20) not null , "
				+ "date date not null, "
				+ "open double default 0 , "
				+ "close double default 0 , "
				+ "max double default 0 , "
				+ "min double default 0 , "
				+ "volumn bigint default 0 , "
				+ "updown double default 0 , "
				+ "pure double default 0 , "
				+ "total double default 0 , "
				+ "companySum int default 0 , "
				+ "leader varchar(10), "
				+ "leaderName varchar(20), "
				+ "leaderPrice double default 0 , "
				+ "leaderUpdown double default 0 , "
				+ "primary key(date) "
				+ ") "
				+ "ENGINE=InnoDB DEFAULT CHARSET=utf8;";
		public static final String  insert= " ( "
				+ "industry_name , "
				+ "date , "
				+ "open , "
				+ "close , "
				+ "max , "
				+ "min , "
				+ "volumn , "
				+ "updown , "
				+ "pure , "
				+ "total , "
				+ "companySum , "
				+ "leader , "
				+ "leaderName , "
				+ "leaderPrice , "
				+ "leaderUpdown ) "
				+ "VALUES ( "
				+ "? , ? , ? , ? , ? , ? , ? , "
				+ "? , ? , ? , ? , ? , ? , ? , ? "
				+ ");";
		public static final String selectStock="SELECT "
				+ "open , "
				+ "high , "
				+ "close , "
				+ "low , "
				+ "volumn , "
				+ "adj_price , "
				+ "pe_ttm , "
				+ "pb , "
				+ "stock_name "
				+ "FROM ";
		public static final String seleTail=" where date = ? ;";
	}
	
	public static final String tailBase=" ("
			+ "date date not null, "
			+ "stock_name varchar(20), "
			+ "open double default 0, "
			+ "high double default 0, "
			+ "low double default 0, "
			+ "close double default 0, "
			+ "volumn int default 0, "
			+ "adj_price double default 0,  "
			+ "turnover double default 0,  "
			+ "pe_ttm double default 0,  "
			+ "pb double default 0,  "
			+ "industry varchar(20), "
			+ "PMA5_day double default 0, "
			+ "PMA5_week double default 0, "
			+ "PMA5_month double default 0, "
			+ "PMA10_day double default 0, "
			+ "PMA10_week double default 0, "
			+ "PMA10_month double default 0, "
			+ "PMA30_day double default 0, "
			+ "PMA30_week double default 0, "
			+ "PMA30_month double default 0, "
			+ "RSI6 double default 0, "
			+ "RSI12 double default 0, "
			+ "RSI24 double default 0, "
			+ "BIAS6 double default 0, "
			+ "BIAS12 double default 0, "
			+ "BIAS24 double default 0, "
			+ "K double default 0, "
			+ "D double default 0, "
			+ "J double default 0, "
			+ "DIF double default 0, "
			+ "DEA double  default 0, "
			+ "MACDBar double default 0, "
			+ "poly double default 0, "
			+ "primary key(date)) "
	 		+ "ENGINE=InnoDB DEFAULT CHARSET=utf8;";
	public static final String CreateIndustry_Stock="CREATE TABLE industry_stock ("
			+ "stock_id varchar(10) not null , "
			+ "stock_name varchar(20) , "
			+ "industry varchar(20) , "
			+ "primary key(stock_id)"
			+ ") "
			+ "ENGINE=InnoDB DEFAULT CHARSET=utf8;";
	public static final String insertIndustry_Stock="INSERT INTO industry_stock ( "
			+ "stock_id , "
			+ "stock_name , "
			+ "industry "
			+ ") "
			+ "VALUES ( "
			+ "? , ? , ? "
			+ ");";
	
	public static final String Insert="INSERT INTO ";
	public static final String insTailBase= " ( date , "
			+ "stock_name , "
			+ "open , "
			+ "high , "
			+ "low , "
			+ "close , "
			+ "volumn , "
			+ "adj_price , "
			+ "turnover , "
			+ "pe_ttm , "
			+ "pb , "
			+ "industry , "
			+ "PMA5_day , "
			+ "PMA5_week , "
			+ "PMA5_month , "
			+ "PMA10_day , "
			+ "PMA10_week , "
			+ "PMA10_month , "
			+ "PMA30_day , "
			+ "PMA30_week , "
			+ "PMA30_month , "
			+ "RSI6 , "
			+ "RSI12 , "
			+ "RSI24 , "
			+ "BIAS6 , "
			+ "BIAS12 , "
			+ "BIAS24 , "
			+ "K , "
			+ "D , "
			+ "J , "
			+ "DIF , "
			+ "DEA , "
			+ "MACDBar , "
			+ "poly "
			+ ") "
			+ "VALUES ( "
			+ "? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , "
			+ "? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? "
			+ ");";
	
	public static final String CreaBench="create table benchmark "
			+ "( date timestamp not null,"
			+ "bench_id varchar(80) not null,"
			+ " bench_name varchar(150), "
			+ "open double default 0, "
			+ "high double default 0, "
			+ "low double default 0, "
			+ "close double default 0, "
			+ "volumn int default 0, "
			+ "adj_price double default 0,  "
			+ "transaction bigint default 0,  "
			+ "marketvalue bigint  default 0, "
			+ "flow bigint default 0, "
			+ "PMA double default 0, "
			+ "PMA5_day double default 0, "
			+ "PMA5_week double default 0, "
			+ "PMA5_month double default 0, "
			+ "PMA10_day double default 0, "
			+ "PMA10_week double default 0, "
			+ "PMA10_month double default 0, "
			+ "PMA30_day double default 0, "
			+ "PMA30_week double default 0, "
			+ "PMA30_month double default 0, "
			+ "RSI6 double default 0, "
			+ "RSI12 double default 0, "
			+ "RSI24 double default 0, "
			+ "BIAS6 double default 0, "
			+ "BIAS12 double default 0, "
			+ "BIAS24 double default 0, "
			+ "K double default 0, "
			+ "D double default 0, "
			+ "J double default 0, "
			+ "DIF double default 0, "
			+ "DEA double  default 0, "
			+ "MACDBar double default 0, "
			+ "poly double default 0, "
			+ "primary key(bench_id)) "
			+ "ENGINE=InnoDB DEFAULT CHARSET=utf8;";
	
}
